; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wiscore_rak11200]
platform = espressif32
board = wiscore_rak11200
framework = arduino
lib_deps =
	beegee-tokyo/RUI3-Arduino-Library
build_flags = 
	-DUSE_WB_IO2=1 ; Required for WisBlock Base Board
	-DMY_DEBUG=1   ; Enable to get library debug output
	
; [env:featheresp32]
; platform = espressif32
; board = featheresp32
; framework = arduino
; lib_deps =
; 	beegee-tokyo/RUI3-Arduino-Library
	
